Add secure connect bundle support
datastax-ext/astra-go-sdk pull request #40
Opened 2022-12-08 02:39 UTC by SpencerC

- Borrows bundle parsing code from https://github.com/datastax/cql-proxy/blob/bc72398f86e2852d058a3280dc5e33e031b4a76d/astra/bundle.go.
- Refactors `NewStaticTokenClient` constructor to support an endpoint connection with a custom TLS config or a secure connect bundle.
- Adds support for testing with a live Astra backend (much faster than testcontainers).

2022-12-08 21:39 UTC, aar0np requested changes

2022-12-08 21:39 UTC, aar0np commented on main_test.go
> +		_, err = c.Query(`CREATE KEYSPACE IF NOT EXISTS example WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor' : 1}`).Exec()
Astra DB does not allow keyspaces to be created programatically.  Maybe skip testing this part?

2022-12-08 22:26 UTC, SpencerC commented on main_test.go
> +		_, err = c.Query(`CREATE KEYSPACE IF NOT EXISTS example WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor' : 1}`).Exec()
It is skipped in online testing. Containerized testing will not work without this though.

2022-12-09 13:44 UTC, aar0np approved these changes

2022-12-09 13:45 UTC, merged